source 'https://rubygems.org'


gem 'faker'
gem 'rails', '4.2.4'
gem 'acts_as_votable'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'nokogiri'
gem 'mechanize'
gem 'devise'
gem 'ransack'
gem 'bootstrap-sass', '~> 3.3.6'

group :development, :test do
  gem 'byebug'
  gem 'pry-rails'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

